// Generated by gencpp from file cv_basics/aruco_data.msg
// DO NOT EDIT!


#ifndef CV_BASICS_MESSAGE_ARUCO_DATA_H
#define CV_BASICS_MESSAGE_ARUCO_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cv_basics
{
template <class ContainerAllocator>
struct aruco_data_
{
  typedef aruco_data_<ContainerAllocator> Type;

  aruco_data_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  aruco_data_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::cv_basics::aruco_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cv_basics::aruco_data_<ContainerAllocator> const> ConstPtr;

}; // struct aruco_data_

typedef ::cv_basics::aruco_data_<std::allocator<void> > aruco_data;

typedef boost::shared_ptr< ::cv_basics::aruco_data > aruco_dataPtr;
typedef boost::shared_ptr< ::cv_basics::aruco_data const> aruco_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cv_basics::aruco_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cv_basics::aruco_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cv_basics::aruco_data_<ContainerAllocator1> & lhs, const ::cv_basics::aruco_data_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cv_basics::aruco_data_<ContainerAllocator1> & lhs, const ::cv_basics::aruco_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cv_basics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cv_basics::aruco_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cv_basics::aruco_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_basics::aruco_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cv_basics::aruco_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_basics::aruco_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cv_basics::aruco_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cv_basics::aruco_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::cv_basics::aruco_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::cv_basics::aruco_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cv_basics/aruco_data";
  }

  static const char* value(const ::cv_basics::aruco_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cv_basics::aruco_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::cv_basics::aruco_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cv_basics::aruco_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct aruco_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cv_basics::aruco_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cv_basics::aruco_data_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CV_BASICS_MESSAGE_ARUCO_DATA_H
